### ISSUE TITLE
Unable to extract tables from following the pdf

### ISSUE THREAD

**Issue by MrKimmich** [xavctn/img2table#126]
- I have gone through the code and found that currently it doesn't support to extract text from table which are like hybrid between bordered tables and borderless tables PFA
- Can please check this and let me know if you are able to extract tables from below pdf

[ip-test.pdf](https://github.com/xavctn/img2table/files/13061302/ip.pdf)

**Comment by xavctn** [comment]
Hello,

In your file, the 6.2 and 6.4 tables are extracted properly.
For the 6.3 table, as it spans over 3 pages, the "bordered table" algorithm is not able to detect it. 
When it comes to the "borderless table" algorithm, it requires by design a table with at least 3 columns in order to avoid detecting a lot of BS, that is why it also won't work.
