### ISSUE TITLE
Extraction of Mixed Tabular and Non-Tabular Data?

### ISSUE THREAD

**Issue by snehitvaddi** [xavctn/img2table#131]
I'm interested in using img2table for document text extraction and have documents that feature both tabular and non-tabular text. Can img2table extract both data types within the same workflow? My objective is to automate the extraction process and save the results in a structured, readable format for subsequent data handling tasks.

Appreciate your insights on this.

**Comment by xavctn** [comment]
Hi,

Basically, you can just use the library to detect the tables positions and not run any OCR with it by not setting any ocr in the `extract_tables` method.

You can perform the OCR externally (so that you have the whole document text at your disposal) and match it with the tables/cells positions afterward yourself. 

To extract cell coordinates from a table, you can use this kind of code : 
```python
for id_row, row in enumerate(table.content.values()):
    for id_col, cell in enumerate(row):
        x1 = cell.bbox.x1
        y1 = cell.bbox.y1
        x2 = cell.bbox.x2
        y2 = cell.bbox.y2
```

**Comment by nissansz** [comment]
> Hi,
> 
> Basically, you can just use the library to detect the tables positions and not run any OCR with it by not setting any ocr in the `extract_tables` method.
> 
> You can perform the OCR externally (so that you have the whole document text at your disposal) and match it with the tables/cells positions afterward yourself.
> 
> To extract cell coordinates from a table, you can use this kind of code :
> 
> ```python
> for id_row, row in enumerate(table.content.values()):
>     for id_col, cell in enumerate(row):
>         x1 = cell.bbox.x1
>         y1 = cell.bbox.y1
>         x2 = cell.bbox.x2
>         y2 = cell.bbox.y2
> ```

How to merge cells with rowspan and colspan?
