### ISSUE TITLE
Issue with table extraction

### ISSUE THREAD

**Issue by johnnynguyen98** [xavctn/img2table#25]
I have tried to extract tables from a scanned PDF with landscape orientation using OCR Tesseract. The extraction fails to detect the entire table and hence, misses the column on the left margin ('ALDERSHO' in the screenshot below)  and column on the right margin ('36,974/n17,786/n8,552/n1,038' in the screenshot below). Is there a way to fix this? Thanks!

<img width="738" alt="Issue" src="https://user-images.githubusercontent.com/80743602/221391456-c4849458-8c78-495a-ba93-7a143558795e.PNG">

**Comment by xavctn** [comment]
From what I can see, the outside left and right columns are not being identified because they are not delimited by a border, contrary to the other columns.
As of now, I do not really have an idea on how to handle those cases without breaking table detection on "regular" table layouts.

We can keep this issue open as a reminder

**Comment by johnnynguyen98** [comment]
Do you have any suggestions on how I can solve this issue for this task? Other methods that I can use to supplement my current extraction or different approaches that I should look into and consider? Thanks!

**Comment by xavctn** [comment]
You can check out different table recognition frameworks, most of them are deep learning methods ([Paddle has an easy to use implementation](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart_en.md#224-table-recognition))
They will probably give you some good results over your documents.
