### ISSUE TITLE
Img2Table and PaddleOCR causing inconsistency

### ISSUE THREAD

**Issue by PDM996** [xavctn/img2table#42]
Hi,

Thank you for your previous suggestion on using PaddleOCR, it did do a much better job, although it missed some numbers.
Any suggestion on how to improve the results? should I try to follow the paddle documentation? I am a user...not an expert on these things. I have learned the hard way, by doing and getting stuck.

I recently had to install some other libraries which have been causing the following message to pop up:

_The environment is inconsistent, please check the package plan carefully_
_The following packages are causing the inconsistency:_

- _esri/win-64::paddleocr==2.0.6=py39_3_

This has caused the installation to be so slow, I had to stop it. I am running python 3.9.16 on a windows machine.
Why do you think it is happening?
The only way I could solve it, was to update the conda installation via `conda install conda` and `conda update --all` . However, that caused the Img2Table and PaddleOCR not working, unless I reinstalled paddle via `pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html` .

I am in the process of creating different environments to keep them separate, and use the one with Img2Table and paddle of OCR only, and doing any other data analysis in the other environment/s. is there a better way of managing this? I really would prefer not to have to jump in and out of environment, and having a project in multiple notebooks.

Thanks in advance for any help.

Regards,
Pietro

**Comment by xavctn** [comment]
Hi,

First, regarding the OCR, Paddle is the most accurate open-source OCR I know of (if you know some better ones, I could implement support for those). If you wanna get better results, I do not think there are any other alternatives to using a commercial OCR as Textract or GCP vision.

For your environment, I do not really know, I'm not using anaconda as my package manager and I create a new virtual environment for each project I work on in order to avoid getting issues with conflicting packages (I'm also developing on windows).
It is in general the best practice and I would encourage you to do the same if you want to avoid headaches.

Lastly, there does not seem to be any issue between the library and PaddleOCR as it works well in the CI for python versions from 3.7 to 3.11
