### ISSUE TITLE
Compatibility of EasyOCR

### ISSUE THREAD

**Issue by akshayrakate** [xavctn/img2table#46]
How can we extract text using **EasyOCR**  ? Is there any way to add EasyOCR compatiblity ?

**Comment by xavctn** [comment]
Hi,

It should be fairly easy to add integration with EasyOCR. I will work on it.

**Comment by xavctn** [comment]
Ok, I tried to integrate it and developed the code in order to integrate it.
Somehow, limitations in opencv-python-headless in the last available version of EasyOCR create conflict with other libraries and result in failure of environment creation.

As long as a new version fixing those issues is not released, I am unable to integrate it into the library without causing major issues.
I will keep the branch with the relevant code and update it when a new release is published.

**Comment by xavctn** [comment]
Meanwhile, if your environment permits it, you can reuse the [implementation](https://github.com/xavctn/img2table/blob/EasyOCR/src/img2table/ocr/easyocr.py) I made and tou should be able to use the library with EasyOCR

**Comment by akshayrakate** [comment]
Hey @xavctn EasyOCR ocr_instance is working fine. Thanks for your amazing work.
