### ISSUE TITLE
Effort to add a new OCR to the library

### ISSUE THREAD

**Issue by 004Ajay** [xavctn/img2table#47]
Hi, I have developed a neural network using TensorFlow to classify numbers from 1-7 and the model is saved as an h5 file. How can I add that h5 file to this library's OCR file (from img2table.ocr import my_ocr)?
I have tried many ways but none have worked. What are the changes that I have to make to attain my goal?

**Comment by xavctn** [comment]
Hello,
In order to integrate a custom OCR, it has to be an instance of the [OCRInstance](https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/base.py#L8) class which basically runs the OCR on an image and returns a specific polars LazyFrame.

You can check the [PaddleOCR](https://github.com/xavctn/img2table/blob/main/src/img2table/ocr/paddle.py) implementation as an example.
