### ISSUE TITLE
Not able to read the PDF.

### ISSUE THREAD

**Issue by kenadave** [xavctn/img2table#69]
Hi,

While reading the PDF, I am getting blank Sheet as an output. Requesting for the help.

[File](https://drive.google.com/file/d/16pLEq_t8RCEDAwDm47Ihk1WviHiTGAIy/view?usp=sharing)

**Comment by xavctn** [comment]
Hello,
I think that there is not really a chance that the implemented algorithm will pick up your tables accurately because :

1. It assumes that the provided image/PDF is straight which is not the case
2. The tables are probably too "dense" in order to be detected properly.

You should try CNN based models for table detection, they might be better on those type of documents

**Comment by kenadave** [comment]
> Hello, I think that there is not really a chance that the implemented algori
/thm will pick up your tables accurately because :
> 
> 1. It assumes that the provided image/PDF is straight which is not the case
> 2. The tables are probably too "dense" in order to be detected properly.
> 
> You should try CNN based models for table detection, they might be better on those type of documents

1) I can rotate it the PDF right if not being straight is a problem? Correct me please if I am wrong
2) for CNN models, is it possible to share any examples or tutorials please? I am new in this area
